matrix:
  include:
    - language: node_js
      node_js:
        - 10
      before_install:
        - cd client
      install:
        - npm install 
        - npm install --save-dev enzyme enzyme-adapter-react-16 enzyme-to-json
      script:
        - npm test
